### ISSUE TITLE
运行run.py报错

### ISSUE THREAD

**Issue by ProjectMoss** [hsu1943/sys-status#2]
Traceback (most recent call last):
  File "run.py", line 75, in <module>
    "size": disk_info[1],
TypeError: 'bool' object is not subscriptable

**Comment by hsu1943** [comment]
我这边在 centos7.2 上使用的。

确认一下 `df -h` 命令输出的数据，我这边是这样的：

```bash
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        3.7G     0  3.7G   0% /dev
tmpfs           3.7G  4.0K  3.7G   1% /dev/shm
tmpfs           3.7G  880K  3.7G   1% /run
tmpfs           3.7G     0  3.7G   0% /sys/fs/cgroup
/dev/vda1        40G   29G  8.5G  78% /
tmpfs           756M  4.0K  756M   1% /run/user/1001
```

如果你的服务器输出的不是这样的，那你需要根据你的输出做一些修改，这部分代码很简单，就是取每一行的输出进行格式化，存储要监控的磁盘的数据。
